server:
  port: 8901
spring:
  application:
    name: nacos-provider
  cloud:
    nacos:
      discovery:
        server-addr: nacos01:8848

management:
  endpoint:
    web:
      exposure:
        include:'*'